### ISSUE TITLE
can't change broker

### ISSUE THREAD

**Issue by andysc** [seanmtracey/digital-twin#16]
I got the broker address wrong at the beginning, and now I can't change it

**Comment by seanmtracey** [comment]
In the editor for the twin, the broker address and the twin name can be changed by editing the toolbar at the top of the UI.

Any changes made will be persisted after the input loses focus. Twins already being displayed somewhere will automatically update to the new connection details within 15 seconds.

**Comment by seanmtracey** [comment]
Ability to edit twin name / broker details will also be included in the sub-menu of each twin in the main twin selection UI.
