### ISSUE TITLE
UX: configure dialogue needs an OK/Done button

### ISSUE THREAD

**Issue by andysc** [seanmtracey/digital-twin#20]
I feel I want to click a positive confirmation button to close the dialogue, like OK or Done (as in Node-RED) to save the changes, with the option of a Cancel to close abandoning changes.

**Comment by seanmtracey** [comment]
Yup, totally agree, just haven't gotten around to that bit atm.

**Comment by seanmtracey** [comment]
Dialogs have been added a while ago now and shipped :+1:
