### ISSUE TITLE
how do you delete a node?

### ISSUE THREAD

**Issue by andysc** [seanmtracey/digital-twin#21]
in NR, FWIW, there's a Delete button in the configuration dialogue box. And ctrl-X / edit->cut / backspace also do it. You'll need ctrl-Z then, also, so I can undo that mistake. And normal copy/paste, of course, which I'm sure are on the list

**Comment by seanmtracey** [comment]
Right now, if you have the node selected, you can press CTRL + Backspace on your keyboard to delete. Will add an option to the configuration panel when addressing #20
