### ISSUE TITLE
broker specification assumes port is 1883

### ISSUE THREAD

**Issue by andysc** [seanmtracey/digital-twin#24]
if you put broker as mqtt://xxxxx:1885, it doesn't connect. The code most likely assumes port is 1883 and ignores any over-ride.

**Comment by seanmtracey** [comment]
Huge oversight on my part, will remedy with default to 1883, but with a user-specified override.

**Comment by seanmtracey** [comment]
Remedied in 18cac81f604afcea4d00a566403d10f60d93cb71. User is now able to set port on twin creation and configure later in the edit view. If omitted, port defaults to 1883.
