### ISSUE TITLE
hard to know if broker is correct

### ISSUE THREAD

**Issue by andysc** [seanmtracey/digital-twin#25]
It would be really useful to have an indicator in the editor view to confirm the broker address, port and credentials (yet to come) are correct... maybe a RAG blob next to it?
I don't know if the back-end tries to connect to the broker in edit mode, but it could.
Or, have a connected indicator in a corner of the run-time view also, so you know if it loses connection and why things aren't changing. 
Of course there are two levels of connection - web socket to cloud  and broker connection from back-end.

**Comment by seanmtracey** [comment]
RAG blob is a great idea. 

Was planning on a more verbose connection dialog in the editor. Right now, in the view mode for each twin, a connected / disconnected dialog will appear depending on the connection to the MQTT broker OR the WebSocket connection to the Digital Twin service. This could be a little clearer about what's going wrong too.

**Comment by seanmtracey** [comment]
The ability to test connectivity has been added in a24d9d60bc3232357c67a34f5bacac678ef95a54
