### ISSUE TITLE
set object to transparent

### ISSUE THREAD

**Issue by andysc** [seanmtracey/digital-twin#27]
In the colour picker for the rule, can we have "transparent" as a colour option?
It looks like it might be there but crossed out (and unselectable) in the top-left corner of the picker?

**Comment by seanmtracey** [comment]
How the color selector appears is down to how the browser vendor / OS implements the `input[type="color"]` input. 

I don't have transparency in my picker either, but will look into alternatives to enable it as I intended to have invisible nodes from the start

**Comment by seanmtracey** [comment]
Done :+1:
